#ifndef IDK_CORE_GAMEPAD_STATE_H
#define IDK_CORE_GAMEPAD_STATE_H

#include <stdint.h>
typedef enum idk_gamepad_button
{
    IDK_GAMEPAD_BUTTON_A = 0,
    IDK_GAMEPAD_BUTTON_B = 1,
    IDK_GAMEPAD_BUTTON_X = 2,
    IDK_GAMEPAD_BUTTON_Y = 3,
    IDK_GAMEPAD_BUTTON_LEFT_BUMPER = 4,
    IDK_GAMEPAD_BUTTON_RIGHT_BUMPER = 5,
    IDK_GAMEPAD_BUTTON_BACK = 6,
    IDK_GAMEPAD_BUTTON_START = 7,
    IDK_GAMEPAD_BUTTON_GUIDE = 8,
    IDK_GAMEPAD_BUTTON_LEFT_THUMB = 9,
    IDK_GAMEPAD_BUTTON_RIGHT_THUMB = 10,
    IDK_GAMEPAD_BUTTON_DPAD_UP = 11,
    IDK_GAMEPAD_BUTTON_DPAD_RIGHT = 12,
    IDK_GAMEPAD_BUTTON_DPAD_DOWN = 13,
    IDK_GAMEPAD_BUTTON_DPAD_LEFT = 14,
    IDK_GAMEPAD_BUTTON_LAST = IDK_GAMEPAD_BUTTON_DPAD_LEFT,
    IDK_GAMEPAD_BUTTON_CROSS = IDK_GAMEPAD_BUTTON_A,
    IDK_GAMEPAD_BUTTON_CIRCLE = IDK_GAMEPAD_BUTTON_B,
    IDK_GAMEPAD_BUTTON_SQUARE = IDK_GAMEPAD_BUTTON_X,
    IDK_GAMEPAD_BUTTON_TRIANGLE = IDK_GAMEPAD_BUTTON_Y
} idk_gamepad_button_t;

typedef enum idk_gamepad_axis
{
    IDK_GAMEPAD_AXIS_LEFT_X = 0,
    IDK_GAMEPAD_AXIS_LEFT_Y = 1,
    IDK_GAMEPAD_AXIS_RIGHT_X = 2,
    IDK_GAMEPAD_AXIS_RIGHT_Y = 3,
    IDK_GAMEPAD_AXIS_LEFT_TRIGGER = 4,
    IDK_GAMEPAD_AXIS_RIGHT_TRIGGER = 5,
    IDK_GAMEPAD_AXIS_LAST = IDK_GAMEPAD_AXIS_RIGHT_TRIGGER
} idk_gamepad_axis_t;

#endif
