#ifndef IDK_CORE_MOUSE_BUTTONS_H
#define IDK_CORE_MOUSE_BUTTONS_H

#include "idk/core/common.h"

IDK_C_API_BEGIN

typedef enum idk_mouse_button
{
	IDK_MOUSE_BUTTON_1 = 0,
	IDK_MOUSE_BUTTON_2 = 1,
	IDK_MOUSE_BUTTON_3 = 2,
	IDK_MOUSE_BUTTON_4 = 3,
	IDK_MOUSE_BUTTON_5 = 4,
	IDK_MOUSE_BUTTON_6 = 5,
	IDK_MOUSE_BUTTON_7 = 6,
	IDK_MOUSE_BUTTON_8 = 7,
	IDK_MOUSE_BUTTON_LAST = IDK_MOUSE_BUTTON_8,
    IDK_MOUSE_BUTTON_LEFT = IDK_MOUSE_BUTTON_1,
    IDK_MOUSE_BUTTON_RIGHT = IDK_MOUSE_BUTTON_2,
    IDK_MOUSE_BUTTON_MIDDLE = IDK_MOUSE_BUTTON_3
} idk_mouse_button_t;

IDK_C_API_END

#endif
